### ISSUE TITLE
galib compilation issue

### ISSUE THREAD

**Issue by kornelski** [hoehrmann/pngwolf#6]
I'm not sure if it's fault in galib or pngwolf.

Both gcc 4.9 and clang fail to compile (tested galib 2.46 and galib 2.47):

<pre>
[  2%] Building CXX object CMakeFiles/pngwolf.dir/pngwolf.cxx.o
In file included from /www/pngwolf/galib/ga/GA1DArrayGenome.h:178:0,
                 from /www/pngwolf/galib/ga/ga.h:167,
                 from /www/pngwolf/pngwolf.cxx:39:
/www/pngwolf/galib/ga/GA1DArrayGenome.C: In instantiation of 'GA1DArrayAlleleGenome<T>::GA1DArrayAlleleGenome(unsigned int, const GAAlleleSet<T>&, GAGenome::Evaluator, void*) [with T = PngFilter; GAGenome::Evaluator = float (*)(GAGenome&)]':
/www/pngwolf/pngwolf.cxx:872:52:   required from here
/www/pngwolf/galib/ga/GA1DArrayGenome.C:225:75: error: 'initializer' was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
   initializer(GA1DArrayAlleleGenome<T>::DEFAULT_1DARRAY_ALLELE_INITIALIZER);
                                                                           ^
/www/pngwolf/galib/ga/GA1DArrayGenome.C:225:75: note: declarations in dependent base 'GAGenome' are not found by unqualified lookup
/www/pngwolf/galib/ga/GA1DArrayGenome.C:225:75: note: use 'this->initializer' instead
/www/pngwolf/galib/ga/GA1DArrayGenome.C:226:67: error: 'mutator' was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
   mutator(GA1DArrayAlleleGenome<T>::DEFAULT_1DARRAY_ALLELE_MUTATOR);
                                                                   ^
/www/pngwolf/galib/ga/GA1DArrayGenome.C:226:67: note: declarations in dependent base 'GAGenome' are not found by unqualified lookup
/www/pngwolf/galib/ga/GA1DArrayGenome.C:226:67: note: use 'this->mutator' instead
/www/pngwolf/galib/ga/GA1DArrayGenome.C:227:73: error: 'comparator' was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
   comparator(GA1DArrayAlleleGenome<T>::DEFAULT_1DARRAY_ALLELE_COMPARATOR);
                                                                         ^
/www/pngwolf/galib/ga/GA1DArrayGenome.C:227:73: note: declarations in dependent base 'GAGenome' are not found by unqualified lookup
/www/pngwolf/galib/ga/GA1DArrayGenome.C:227:73: note: use 'this->comparator' instead
/www/pngwolf/galib/ga/GA1DArrayGenome.C:228:71: error: 'crossover' was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
   crossover(GA1DArrayAlleleGenome<T>::DEFAULT_1DARRAY_ALLELE_CROSSOVER);
                                                                       ^
/www/pngwolf/galib/ga/GA1DArrayGenome.C:228:71: note: declarations in dependent base 'GAGenome' are not found by unqualified lookup
/www/pngwolf/galib/ga/GA1DArrayGenome.C:228:71: note: use 'this->crossover' instead
make[2]: *** [CMakeFiles/pngwolf.dir/pngwolf.cxx.o] Error 1
make[1]: *** [CMakeFiles/pngwolf.dir/all] Error 2
</pre>

clang:

<pre>
[  2%] Building CXX object CMakeFiles/pngwolf.dir/pngwolf.cxx.o
In file included from /www/pngwolf/pngwolf.cxx:39:
In file included from /www/pngwolf/galib/ga/ga.h:167:
In file included from /www/pngwolf/galib/ga/GA1DArrayGenome.h:178:
/www/pngwolf/galib/ga/GA1DArrayGenome.C:225:3: error: use of undeclared identifier 'initializer'
  initializer(GA1DArrayAlleleGenome<T>::DEFAULT_1DARRAY_ALLELE_INITIALIZER);
  ^
/www/pngwolf/galib/ga/GA1DArrayGenome.C:226:3: error: use of undeclared identifier 'mutator'
  mutator(GA1DArrayAlleleGenome<T>::DEFAULT_1DARRAY_ALLELE_MUTATOR);
  ^
/www/pngwolf/galib/ga/GA1DArrayGenome.C:241:3: error: use of undeclared identifier 'initializer'
  initializer(GA1DArrayAlleleGenome<T>::DEFAULT_1DARRAY_ALLELE_INITIALIZER);
  ^
/www/pngwolf/galib/ga/GA1DArrayGenome.C:242:3: error: use of undeclared identifier 'mutator'
  mutator(GA1DArrayAlleleGenome<T>::DEFAULT_1DARRAY_ALLELE_MUTATOR);
</pre>

**Comment by joeyhoer** [comment]
Same issue here. I was able to compile with clang on OS 10.9 by following a tip found at http://clang.debian.net/status.php?version=3.3&key=USE_OF_UNDECLARED_IDENTIFIER

Update the following files files:

```
galib/ga/GA1DArrayGenome.C
galib/ga/GA2DArrayGenome.C
galib/ga/GA3DArrayGenome.C
```

Any instance of:

```
initializer(…);
mutator(…);
comparator(…);
crossover(…);
```

Replace with:

```
this->initializer(…);
this->mutator(…);
this->comparator(…);
this->crossover(…);
```

We should probably add to / write another patch file (the `sevenzip920` patch didn't work for me, so I had to apply those changes manually as well – I believe the line numbers were wrong).

**Comment by TPS** [comment]
@pornel @joeyhoer @DataWraith @liugoanywhere: @jibsen solves this via https://github.com/jibsen/pngwolf-zopfli/commit/ea219775bba1143ba1ee74cbc13c6104042a1283 in [his own fork](https://github.com/jibsen/pngwolf-zopfli), & still keeping it current.  Do you want to close this, @pornel, & migrate over to that?
